### ISSUE TITLE
pygrib fails to load due to missing libhdf5.so.10

### ISSUE THREAD

**Issue by akrherz** [conda-forge/pygrib-feedstock#19]
I am using a currently up-to-date conda-forge (sans pandas 0.21.0) python2.7 on linux 64 bit and can not import pygrib
```
$ python
Python 2.7.14 | packaged by conda-forge | (default, Nov  4 2017, 10:15:28) 
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pygrib
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: libhdf5.so.10: cannot open shared object file: No such file or directory
```

```
$ conda inspect linkages pygrib
pygrib
------

curl-7.55.1-0:
    libcurl.so.4 (lib/libcurl.so.4)

ecmwf_grib-1.23.1-0:
    libgrib_api.so (lib/libgrib_api.so)

hdf4-4.2.13-0:
    libdf.so.0 (lib/libdf.so.0)
    libmfhdf.so.0 (lib/libmfhdf.so.0)

hdf5-1.10.1-1:
    libhdf5.so.101 (lib/libhdf5.so.101)
    libhdf5_hl.so.100 (lib/libhdf5_hl.so.100)

jasper-1.900.1-4:
    libjasper.so.1 (lib/libjasper.so.1)

jpeg-9b-2:
    libjpeg.so.9 (lib/libjpeg.so.9)

krb5-1.14.2-0:
    libcom_err.so.3 (lib/libcom_err.so.3)
    libgssapi_krb5.so.2 (lib/libgssapi_krb5.so.2)
    libk5crypto.so.3 (lib/libk5crypto.so.3)
    libkrb5.so.3 (lib/libkrb5.so.3)
    libkrb5support.so.0 (lib/libkrb5support.so.0)

libnetcdf-4.4.1.1-10:
    libnetcdf.so.11 (lib/libnetcdf.so.11)

libpng-1.6.28-2:
    libpng16.so.16 (lib/libpng16.so.16)

libssh2-1.8.0-2:
    libssh2.so.1 (lib/libssh2.so.1)

openssl-1.0.2l-0:
    libcrypto.so.1.0.0 (lib/libcrypto.so.1.0.0)
    libssl.so.1.0.0 (lib/libssl.so.1.0.0)

python-2.7.14-1:
    libpython2.7.so.1.0 (lib/libpython2.7.so.1.0)

zlib-1.2.11-0:
    libz.so.1 (lib/libz.so.1)

system:
    libc.so.6 (/lib64/libc.so.6)
    libdl.so.2 (/lib64/libdl.so.2)
    libm.so.6 (/lib64/libm.so.6)
    libpthread.so.0 (/lib64/libpthread.so.0)
    libresolv.so.2 (/lib64/libresolv.so.2)
    librt.so.1 (/lib64/librt.so.1)
    libutil.so.1 (/lib64/libutil.so.1)
    linux-vdso.so.1 ()

not found:
    libhdf5.so.10 (not found)
```

```
$ conda list pygrib
pygrib                    2.0.2                    py27_1    conda-forge
$ conda list hdf5
hdf5                      1.10.1                        1    conda-forge

```

I tried uninstalling it and reinstalling pygrib without success.  This only started after the hdf5 update

**Comment by dopplershift** [comment]
I can reproduce on my Mac, but it seems like this is actually a problem in the ecmwf_grib package, based on the error coming from libgrib_api.dylib:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: dlopen(/Users/rmay/miniconda3/envs/test-grib/lib/python2.7/site-packages/pygrib.so, 2): Library not loaded: @rpath/libhdf5.10.dylib
  Referenced from: /Users/rmay/miniconda3/envs/test-grib/lib/libgrib_api.dylib
  Reason: image not found
```

Trying to run a tool from the ecmwf_grib packages fails:
```
>./grib_get
dyld: Library not loaded: @rpath/libhdf5.10.dylib
  Referenced from: /Users/rmay/miniconda3/envs/test-grib/bin/./grib_get
  Reason: image not found
[1]    26753 abort      ./grib_get
```

So we should probably try to fix it over there.

**Comment by ocefpaf** [comment]
I did not finish to rebuild all the packages after the `libnetcdf` update to `hdf5 1.10.1` (Travis-CI backlog and day job are in the way.)

I believe that only `ecmwf_grib` is in the way of this issue though. I'll send a PR soon.

**Comment by akrherz** [comment]
@ocefpaf You are amazing! Thank you for all your efforts on conda-forge!  To verify, I updated to ecmwf_grib=1.23.1-1 and pygrib imports!  Horray!

**Comment by ocefpaf** [comment]
Glad it is solved. The move to `hdf 1.10.1`  will probable trigger more issue like that but soon all the key packages will be rebuilt.

**Comment by chirag912** [comment]
Hi, I m having a similar issue as well.

ImportError: dlopen(/Users/chirag912/anaconda/lib/python3.6/site-packages/pygrib.cpython-36m-darwin.so, 2): Library not loaded: /opt/local/lib/libhdf5.100.dylib
  Referenced from: /Users/chirag912/anaconda/lib/libgrib_api.dylib
  Reason: Incompatible library version: libgrib_api.dylib requires version 101.0.0 or later, but libgrib_api.dylib provides version 0.0.0


Can you please guide how to upgrade grip_api ?. Im very new to this so please pardon me of my silly questions.
